services:
  tulipa:
    image: julia:1.10
    container_name: tulipa
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - ../gurobi.lic:/root/gurobi.lic:ro
    stdin_open: true
    tty: true
    command: sleep infinity
    deploy:
      resources:
        limits:
          cpus: "12.0" # Maximum allowed usage
          memory: 24G # Maximum allowed RAM
        reservations:
          cpus: "12.0" # Guaranteed minimum
          memory: 24G # Guaranteed minimum RAM
